services:
  db:
    image: postgres:16
    container_name: prod_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d {POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - prod_net

  app:
    image: ghcr.io/hemang-mishra/jagrati-backend:prod
    container_name: prod_app
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      APP_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:18080:8080"
    networks:
      - prod_net

volumes:
  prod_db_data:

networks:
  prod_net: