services:
  db:
    image: postgres:16
    container_name: staging_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - staging_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - staging_net

  app:
    image: ghcr.io/hemang-mishra/jagrati-backend:staging
    container_name: staging_app
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_ENV: staging
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "127.0.0.1:28080:8080"
    networks:
      - staging_net

volumes:
  staging_db_data:

networks:
  staging_net:
