CREATE TABLE fcm_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    pid        VARCHAR(50)                             NOT NULL,
    device_id  TEXT                                    NOT NULL,
    CONSTRAINT pk_fcm_tokens PRIMARY KEY (id)
);

ALTER TABLE fcm_tokens
    ADD CONSTRAINT uc_fcm_tokens_deviceid UNIQUE (device_id);

ALTER TABLE fcm_tokens
    ADD CONSTRAINT FK_FCM_TOKENS_ON_PID FOREIGN KEY (pid) REFERENCES users (pid);
